# Generated by Django 6.0.6 on 2026-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_capacity',
            field=models.CharField(blank=True, help_text='Example: 5 Tons', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Truck'), ('PICKUP', 'Pickup'), ('TRAILER', 'Trailer'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle')], max_length=30, null=True),
        ),
    ]
